apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: "<MONGODB_URI>"
        - name: PORT
          value: "5001"
        - name: JWT_SECRET
          value: "<JWT_SECRET>"
        - name: NODE_ENV
          value: "production"
        - name: CLOUDINARY_CLOUD_NAME
          value: "<CLOUDINARY_CLOUD_NAME>"
        - name: CLOUDINARY_API_KEY
          value: "<CLOUDINARY_API_KEY>"
        - name: CLOUDINARY_API_SECRET
          value: "<CLOUDINARY_API_SECRET>"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: NodePort
